name: Create Docker Image and Deploy the conatiner
on:
 workflow_call:
jobs:
 build:
  runs-on: self-hosted
  
  steps:
   - name: Checkout
     uses: actions/checkout@v2
    
   - name: Setup BuildX
     uses: docker/setup-buildx-action@v1
     
   - name: Build the docker image
     run: |
        cp -rf /home/ubuntu/actions-runner/_work/Deployment-reusable-workflow/Dockerfile /home/ubuntu/actions-runner/_work/Deployment-reusable-workflow/Deployment-reusable-workflow/
        docker build -t myapp:1.1 .   
 DEV:
  runs-on: self-hosted
  environment: DEV
  needs: build
  steps:
   - name: Set up SSH
     uses: webfactory/ssh-agent@v0.5.1
     with:
      ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
   - name: Build the docker image
     run: |
         scp . ubuntu@172.31.93.103:/home/ubuntu/actions-runner/_work/Deployment-reusable-workflow/Deployment-reusable-workflow/Dockerfile
         docker build -t myapp:1.1 .
   - name: Create and Run docker image on EC2 instance
     run: |
       ssh ubuntu@18.207.225.38 
       docker run --name webdev1 -d -P /home/ubuntu/myapp:1.1
 QA:
  runs-on: self-hosted
  environment: QA
  needs: DEV
  steps:
   - name: Deploying contanier to QA 
     run: docker run --name mywebapp2 -d -P myapp:1.1
 PROD:
  runs-on: self-hosted
  environment: PROD
  needs: QA
  steps:
   - name: Deploying container to PROD
     run: docker run --name mywebapp3 -d -P myapp:1.1
