name: Create Docker Image and Deploy the conatiner
on:
 workflow_call:
jobs:
 build:
  runs-on: self-hosted
  
  steps:
   - name: Checkout
     uses: actions/checkout@v3
    
   - name: Setup BuildX
     uses: docker/setup-buildx-action@v1
     
   - name: Build the docker image
     run: |
        cp -rf /home/ubuntu/actions-runner/_work/Deployment-reusable-workflow/Dockerfile /home/ubuntu/actions-runner/_work/Deployment-reusable-workflow/Deployment-reusable-workflow/
        docker build -t myapp:1.1 .   
 DEV:
  runs-on: self-hosted
  environment: DEV
  needs: build
  steps:
   - name: Build the docker image
     run: |
         scp -r /home/ubuntu/actions-runner/_work/Deployment-reusable-workflow/Deployment-reusable-workflow/Dockerfile ubuntu@DEV:/home/ubuntu/
         ssh ubuntu@DEV docker build -t myapp:1.1 .
   - name: Create and Run docker image on EC2 instance
     run: |
       ssh ubuntu@DEV docker run --name mywebapp1 -d -P myapp:1.1
 QA:
  runs-on: self-hosted
  environment: QA
  needs: DEV
  steps:
   - name: Build the docker image
     run: |
         scp -r /home/ubuntu/actions-runner/_work/Deployment-reusable-workflow/Deployment-reusable-workflow/Dockerfile ubuntu@QA:/home/ubuntu/
         ssh ubuntu@QA docker build -t myapp:1.1 .
   - name: Deploying contanier to QA 
     run: |
       ssh ubuntu@QA docker run --name mywebapp2 -d -P myapp:1.1
 PROD:
  runs-on: self-hosted
  environment: PROD
  needs: QA
  steps:
   - name: Build the docker image
     run: |
         scp -r /home/ubuntu/actions-runner/_work/Deployment-reusable-workflow/Deployment-reusable-workflow/Dockerfile ubuntu@PROD:/home/ubuntu/
         ssh ubuntu@PROD docker build -t myapp:1.1 .
   - name: Deploying container to PROD
     run: |
        ssh ubuntu@PROD docker run --name mywebapp3 -d -P myapp:1.1
