name: Reusable workflow user

on:
 workflow_dispatch:
 push:
  branches:
   - main
jobs:
 do-it:
  runs-on: self-hosted
  
  steps:
   - uses: actions/checkout@v2
   
 docker:
  uses: Sivainfomagnus/Deployment-reusable-workflow/.github/workflows/Deployment.yml@main
